### ISSUE TITLE
ReaPack Crashes Reaper on Ubuntu Linux

### ISSUE THREAD

**Issue by maxxatgit** [cfillion/reapack#25]
I'm a very happy Reaper user, running our favorite DAW on Ubuntu 16.4 64 bit.
At first Reapack didn't show up in the extensions menu, so I started it from the command line to see the errors. It said it couldn't find libcrypto.so.1.1. So I installed openssl 1.1.1, which contains the file libcrypto.so.1.1.

Then, Reaper crashed and wouldn't start at all. So I opened it from the command line again and it said:
swell: dlopen() failed: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by .../.config/REAPER/UserPlugins/reaper_reapack64.so)
Error loading .../.config/REAPER/UserPlugins/reaper_reapack64.so: (null)
Segmentation fault (core dumped)

libstdc++.so6 is in my /usrlib/x86_64-linux-gnu directory, but it's the wrong version? I don't understand. Hoping to get this working, and thanks for the great software!

**Comment by cfillion** [comment]
ReaPack requires libstdc++ for GCC 7.1 or newer (that is libstdc++.so.6.0.23 or newer) because it uses C++17 features. Ubuntu 16.04 only has GCC 5.3.1 and libstdc++.so.6.0.21.

It is possible to install newer versions of GCC on Ubuntu 16.04 using the ubuntu-toolchain-r/ppa PPA as documented here: https://wiki.ubuntu.com/ToolChain#Toolchain_Updates. Ubuntu 18.04 and newer has recent enough versions of GCC and libstdc++ out of the box.

```sh
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-9
sudo apt-get upgrade
```

As for the crash, ReaPack is not being executed in this case so it likely comes from somewhere else. A backtrace or core dump would probably yield more information about it. No luck here trying to reproduce it in a fresh/updated Ubuntu 16.04 virtual machine.

**Comment by maxxatgit** [comment]
Thanks for the info!

Not sure how or why the crash happens, but I had to move reapack64.so out of the plugins folder in order for Reaper to open.

I'm going to update my desktop Ubuntu to 18.04 tomorrow. I'll report back. Thanks in advance for the great software, and for the kind and wise support.
