### ISSUE TITLE
MacOS crash when opening Reaper.

### ISSUE THREAD

**Issue by tylovejoy** [cfillion/reapack#51]
Cannot open Reaper with ReaPack (reaper_reapack-x86_64.dylib) placed in the UserPlugins folder.
I posted the exception details at the bottom of this issue. Here is the full crash output https://pastebin.com/3A9hEjcP

Versions:
MacOS 11.6.7
Reaper 6.61
ReaPack 1.2.4.1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [661]

**Comment by tylovejoy** [comment]
I was using the wrong folder. My apologies.

**Comment by cfillion** [comment]
Fixing the crash, thanks for reporting this!

**Comment by Garvilli** [comment]
I have this same issue right now on my Mac Mini M1, so what is the right folder?

**Comment by cfillion** [comment]
This issue was fixed in v1.2.4.2, if you still have a crash on startup with the latest version it could be something else. The correct folder is UserPlugins in REAPER's resource directory (Options > Show REAPER resource path in explorer/finder) as per the [user guide](https://reapack.com/user-guide#installation). (But it shouldn't crash even if put elsewhere or renamed.)

Please post your crash report so I can investigate your crash.

**Comment by Garvilli** [comment]
Thank you for the reply and I'm sorry I haven't replied back yet. 

There's no crash report as such, just a pop-up with this message: 

**“reaper_sws-arm64.dylib” can’t be opened because Apple cannot check it for malicious software.**
This software needs to be updated. Contact the developer for more information
Safari downloaded this file on 6 February 2023.

I have problems with other pieces of music software on my Mac, but since I'm so very new to MacOS and crazy busy with building our house, I haven't had the patience or stamina to do much about these things, but in general it seems that my Mac has more "safety" settings in place than your average MacOS install

Thank you again for replying to me!

**Comment by Garvilli** [comment]
Alright, got it to work! 

So apparently what I needed to do was: Control-click the app icon [In this case I guess it's not an app, but whatever] and choose "Open", as explained in this link:
https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

This has fixed a ton of other issues for me, such as finally being able to activate the license for Kirchhoff EQ that I bought four months ago, and I'm hoping it will finally make me able to properly install Muse-Hub.

MacOS is turning out to be a complete jank-fest!
