### ISSUE TITLE
FR: Obsolete scripts

### ISSUE THREAD

**Issue by MichaelPilyavskiy** [cfillion/reapack#8]
1. Notify about scripts getting obsolete when syncronizing
2. Move them to /Scripts/Obsolete by default (+ disable this optionally)
3. Remove from ActionList by default (+ disable this optionally)

**Comment by cfillion** [comment]
Since the end goal is to help users stay up to date with the remote repository, how about optionally showing a list of (all) obsolete packages when synchronizing, with a way to select them and optionally uninstall them?

I'm imagining a dialog similar to REAPER's "prompt to save/delete/rename" new files ([this one](https://i.imgur.com/DMGyh0l.png)).
